[workspace]
resolver = "2"
members = ["main", "shared", "client", "server", "bevy_web_server", "bevy_web_client"]

[workspace.dependencies]
bevy = "0.12.1"
hyper = {version = "1.1.0", features = ["server", "http1"]}
hyper-tungstenite = "0.13.0"
tokio = {version = "1.36.0", features = ["full"]}
hyper-util = "0.1.3"
http-body-util = "0.1.0"
uuid = {version = "1.7.0", features = ["v4"]}
futures = "0.3.30"
serde = {version = "1.0.196", features = ["derive"]}
bincode = "1.3.3"
ewebsock = {version = "0.4.0", features = ["tls"]}