[workspace]
resolver = "2"
members = ["main", "core", "client", "server"]

[workspace.dependencies]
bevy = "0.12.1"
hyper = {version = "1.1.0", features = ["server", "http1"]}
hyper-tungstenite = "0.13.0"
tokio = {version = "1.36.0", features = ["full"]}
hyper-util = "0.1.3"
uuid = {version = "1.7.0", features = ["v4"]}